
CREATE TABLE farm (
	id SERIAL PRIMARY KEY,
	user_id SERIAL REFERENCES users(id) NOT NULL,
	name VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_user_id ON farm (user_id);
INSERT INTO farm (user_id, name)
VALUES (3, 'HowFarm4');
SELECT *
FROM farm;